version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      target: development
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file:
      - ./.env
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      backend
    networks:
      - learnlab-network
    


  backend:
    build:
      context: ./backend
      target: development
    ports:
      - "8000:8000"
    # volumes:
    #   - ./backend:/app
    #   - /app/.venv  # Don't mount virtual environment
    env_file:
      - ./.env
    environment:
      - PYTHONPATH=/app
      - DEBUG=True
      - ENVIRONMENT=development
    networks:
      - learnlab-network

  streamlit:
    build:
      context: ./streamlit-ui
      target: development
    ports:
      - "8501:8501"
    volumes:
      - ./streamlit-ui:/app
    env_file:
      - ./.env
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - BACKEND_URL=http://backend:8000
    depends_on:
      backend
    networks:
      - learnlab-network
    
  # airflow:
  #   build:
  #     context: ./airflow
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - ./airflow/dags:/opt/airflow/dags
  #     - ./airflow/logs:/opt/airflow/logs
  #     - ./airflow/plugins:/opt/airflow/plugins
  #   environment:
  #     - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://postgres:postgres@db:5432/airflow
  #     - AIRFLOW__CORE__EXECUTOR=LocalExecutor
  #     - AIRFLOW__CORE__LOAD_EXAMPLES=False
  #     - AIRFLOW__CORE__ENABLE_XCOM_PICKLING=True
  #     - AIRFLOW__WEBSERVER__SECRET_KEY=${AIRFLOW_SECRET_KEY}
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #   networks:
  #     - learnlab-network
  #   healthcheck:
  #     test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 3

volumes:
  postgres_data:
    name: learnlab_postgres_data_dev

networks:
  learnlab-network:
    name: learnlab_network_dev
    driver: bridge