name: 2. Build and Push Docker Images to Docker Hub

on:
  push:
    branches:
      - main
  


env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
  JWT_ALGORITHM: ${{ secrets.JWT_ALGORITHM }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
  AWS_REGION: ${{ secrets.AWS_REGION }}

jobs:
  build:
    name: Build Docker Images
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3
      
      # Step 2: Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      # Step 3: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true

      # Step 4: Configure Docker layer cache
      - name: Set up Docker cache
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-

      # Step 5: Build and push backend Docker image
      - name: Build and push backend Docker image
        env:
          DOCKER_BACKEND_IMAGE: ${{ secrets.DOCKER_USERNAME }}/learnlab-backend
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          target: production
          push: true
          tags: |
            ${{ env.DOCKER_BACKEND_IMAGE }}:latest
            ${{ env.DOCKER_BACKEND_IMAGE }}:${{ github.sha }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache,mode=max

      # Step 6: Build and push Streamlit Docker image
      - name: Build and push Streamlit Docker image
        env:
          DOCKER_STREAMLIT_IMAGE: ${{ secrets.DOCKER_USERNAME }}/learnlab-streamlit
        uses: docker/build-push-action@v4
        with:
          context: ./streamlit-ui
          target: production
          push: true
          tags: |
            ${{ env.DOCKER_STREAMLIT_IMAGE }}:latest
            ${{ env.DOCKER_STREAMLIT_IMAGE }}:${{ github.sha }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache,mode=max
        
      # # Step 4: Build and push Docker images
      # - name: Build and push backend Docker image
      #   uses: docker/build-push-action@v4
      #   with:
      #     context: ./backend
      #     target: production
      #     push: true
      #     tags: |
      #       ${{ env.DOCKER_IMAGE }}:latest
      #       ${{ env.DOCKER_IMAGE }}:${{ github.sha }}
      #     platforms: linux/amd64,linux/arm64

      # # Step 5: Build and push Streamlit Docker image
      # - name: Build and push Streamlit Docker image
      #   uses: docker/build-push-action@v4
      #   with:
      #     context: ./streamlit-ui
      #     target: production
      #     push: true
      #     tags: |
      #       ${{ env.DOCKER_IMAGE }}:latest
      #       ${{ env.DOCKER_IMAGE }}:${{ github.sha }}
      #     platforms: linux/amd64,linux/arm64
