name: Deploy to GCP

on:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types:
      - completed
    branches:
      - main
  push:
    branches:
      - main
    paths:
      - '.github/workflows/03-deploy.yml'

  

env:
  GCP_HOST: '34.57.145.110'
  GCP_USER: 'udaykiran'
  DEPLOYMENT_PATH: '~/learnlab'
  DOCKER_IMAGE: ${{ secrets.DOCKER_USERNAME }}/learnlab-backend
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
  JWT_ALGORITHM: ${{ secrets.JWT_ALGORITHM }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
  AWS_REGION: ${{ secrets.AWS_REGION }}

jobs:
  deploy:
    name: Deploy to GCP
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.GCP_SSH_PRIVATE_KEY }}" > ~/.ssh/gcp_key
          chmod 600 ~/.ssh/gcp_key

      - name: Verify required secrets
        run: |
          required_secrets=(
            DATABASE_URL
            JWT_SECRET_KEY
            JWT_ALGORITHM
            AWS_ACCESS_KEY_ID
            AWS_SECRET_ACCESS_KEY
            AWS_BUCKET_NAME
            AWS_REGION
          )
          for secret in "${required_secrets[@]}"; do
            if [ -z "${!secret}" ]; then
              echo "Error: $secret is not set!"
              exit 1
            fi
          done

      - name: Create .env file
        run: |
          cat > .env << EOL
          DATABASE_URL=${{ secrets.DATABASE_URL }}
          JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}
          JWT_ALGORITHM=${{ secrets.JWT_ALGORITHM }}
          AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_BUCKET_NAME=${{ secrets.AWS_BUCKET_NAME }}
          AWS_REGION=${{ secrets.AWS_REGION }}
          DEBUG=False
          ENVIRONMENT=production
          EOL

      - name: Deploy to GCP
        env:
          SSH_COMMAND: "ssh -i ~/.ssh/gcp_key -o StrictHostKeyChecking=no ${{ env.GCP_USER }}@${{ env.GCP_HOST }}"
          SCP_COMMAND: "scp -i ~/.ssh/gcp_key -o StrictHostKeyChecking=no"
          IMAGE_TAG: ${{ github.sha }}
        run: |
          # Create deployment directory
          ${{ env.SSH_COMMAND }} "mkdir -p ${{ env.DEPLOYMENT_PATH }}"
          

          # Install Docker and Docker Compose
          ${{ env.SSH_COMMAND }} '
            sudo apt update &&
            sudo apt install -y apt-transport-https ca-certificates curl gnupg2 software-properties-common &&
            curl -fsSL https://download.docker.com/linux/debian/gpg | sudo gpg --dearmor --batch --yes -o /usr/share/keyrings/docker-archive-keyring.gpg &&
            echo "deb [arch=arm64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null &&
            sudo apt update &&
            sudo apt install -y docker-ce docker-ce-cli containerd.io &&
            sudo systemctl enable docker &&
            sudo systemctl start docker &&
            sudo curl -L "https://github.com/docker/compose/releases/download/v2.21.0/docker-compose-linux-aarch64" -o /usr/local/bin/docker-compose &&
            sudo chmod +x /usr/local/bin/docker-compose &&
            docker-compose --version &&
            sudo usermod -aG docker $USER
          '

          # Copy files to GCP
          ${{ env.SCP_COMMAND }} docker-compose.prod.yml ${{ env.GCP_USER }}@${{ env.GCP_HOST }}:${{ env.DEPLOYMENT_PATH }}/
          ${{ env.SCP_COMMAND }} .env ${{ env.GCP_USER }}@${{ env.GCP_HOST }}:${{ env.DEPLOYMENT_PATH }}/.env
          
          # Deploy
          ${{ env.SSH_COMMAND }} "cd ${{ env.DEPLOYMENT_PATH }} && \
            docker-compose -f docker-compose.prod.yml pull && \
            docker-compose -f docker-compose.prod.yml up -d"
          
      - name: Verify Deployment
        env:
          SSH_COMMAND: "ssh -i ~/.ssh/gcp_key -o StrictHostKeyChecking=no ${{ env.GCP_USER }}@${{ env.GCP_HOST }}"
        run: |
          sleep 30  # Wait for services to start
          ${{ env.SSH_COMMAND }} "cd ${{ env.DEPLOYMENT_PATH }} && \
            docker-compose -f docker-compose.prod.yml ps && \
            curl -f http://localhost:8000/health || exit 1"
